# Generated by Django 5.2 on 2025-05-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author_name', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('year_pub', models.IntegerField()),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
